ALLOW_MULTIPLE_STOCK_UPDATE: 'true'
MAILER_ADDRESS: smtp.gmail.com
MAILER_PORT: '587'
MAILER_DOMAIN: gmail.com
MAILER_USERNAME: solidusproduction@gmail.com
MAILER_PASSWORD: dJPCC2K8M6dS
MAILER_AUTHENTICATION: plain
AWS_MUMBAI_ACCESS_KEY_ID: AKIAJTXXZWJULGHNI3GA
AWS_MUMBAI_SECRET_ACCESS_KEY: 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
S3_MUMBAI_BUCKET_NAME: shreesarees-store-staging
AWS_REGION: ap-south-1
S3_HOST_NAME: s3-ap-south-1.amazonaws.com
SECRET_KEY_BASE: d70abde15973cbae7af0d92677414703cf2c91289a1c14a2a3dd67d2258c2cad74c400b7f8163f2bc7e6e9e946b3c6cec30c469f552b96bc7a01081bcc999170
USE_INVOICE_NUMBER_FOR_ORDER_NUMBER: 'true'
ALLOW_DELETE_OF_TOP_CATEGORY: 'false'
INVOICE_COPY_MAIL_ADDRESS: 'shreesarees@gmail.com'
ACCESS_CONTROL_ALLOW_ORIGIN: "*"
ACCESS_CONTROL_REQUEST_METHOD: "POST"
WEBSITE_CONTACT_US_EMAIL_TO: "shreesarees@gmail.com"
ROLE_VENDOR: "vendor"
ROLE_ADMIN: "admin"
ROLE_SALESMAN: "salesman"
ROLE_DISPATCHER: "dispatcher"
MAX_NUMBER_OF_PRODUCT: 5